version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Retrieve AWS Account ID and Region dynamically
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - AWS_DEFAULT_REGION=$(aws configure get region) # Assumes region is configured or uses instance metadata
      # Construct ECR repository URI
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/osrm # Use your ECR repo name 'osrm'
      - IMAGE_TAG=us-latest # Specific tag for the US image
      # Login Docker to ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # Build the image - Docker build context is the current directory (.)
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Push completed.
      # (Optional) You can output image details for use in later pipeline stages
      # - printf '[{"name":"osrm-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

# Optional: Define artifacts if you need build outputs for other pipeline stages
# artifacts:
#   files:
#     - imagedefinitions.json